# Generated by Django 2.1.2 on 2019-03-13 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=32, verbose_name='文档标题')),
                ('doc_content', models.TextField(verbose_name='文档内容')),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='附件')),
                ('publish_time', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='点击量')),
                ('doc_remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='文档备注')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文档管理',
                'verbose_name_plural': '文档管理',
            },
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=16, verbose_name='文档类型')),
                ('en_type', models.CharField(default='0', max_length=16, verbose_name='英文名')),
                ('type_remark', models.TextField(blank=True, max_length=128, null=True, verbose_name='文档类型备注')),
            ],
            options={
                'verbose_name': '文档类型管理',
                'verbose_name_plural': '文档类型管理',
            },
        ),
        migrations.AddField(
            model_name='docs',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officialweb.DocType', verbose_name='文档类型'),
        ),
    ]
